### ISSUE TITLE
Not responding in Apple Home

### ISSUE THREAD

**Issue by ileodo** [russtone/homebridge-mi-humidifier#21]
Hi, Thanks for this amazing project! 

While I use it, I release the device show as not responding in the Apple Home time to time, while the other homebridge accessories were fine.

However, after a while (5~10 sec), I can interact with device suddenly.

Is there any state pull interval can be specified?

Thanks.

**Comment by myxa27** [comment]
0|homebridge  | [2020-3-9 10:44:15] [Увлажнитель] getTargetRelativeHumidity { Error: busy.
0|homebridge  |     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
0|homebridge  |     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
0|homebridge  |     at Socket._socket.on (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
0|homebridge  |     at Socket.emit (events.js:127:13)
0|homebridge  |     at UDP.onMessage [as onmessage] (dgram.js:659:8) code: -30012 }
0|homebridge  | [2020-3-9 10:44:41] [Увлажнитель] setTargetRelativeHumidity { Error
0|homebridge  |     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
0|homebridge  |     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
0|homebridge  |     at Socket._socket.on (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
0|homebridge  |     at Socket.emit (events.js:127:13)
0|homebridge  |     at UDP.onMessage [as onmessage] (dgram.js:659:8) code: -5001 }

**Comment by eugensubachev** [comment]
Same problem. No response in Apple Home until i refresh page or tap on humidifier. Same errors in logs.

**Comment by malmentm** [comment]
Which models are affected?

**Comment by eugensubachev** [comment]
skv6001rt

**Comment by malmentm** [comment]
I have noticed the same problem. It seems like the same problem as this Mi Fan 2 plugin has. https://github.com/merdok/homebridge-xiaomi-fan/issues/5

**Comment by myxa27** [comment]
Model - CA1

**Comment by russtone** [comment]
I'm trying to find problem. Could you please collect detailed logs by running homebridge in debug mode?
Here is command:
```sh
DEBUG=miio*,thing* homebridge -D
```

**Comment by myxa27** [comment]
These errors in the log occurred when the humidity level changed. That is, I move the slider to set the humidity level, and at this moment the humidifier loses touch with the home kit for 1-2 seconds, then the connection is restored. Again, move the slider, and again the connection disappears.
Below is the log using the command:
`DEBUG=miio*,thing* homebridge -D`

`[2020-3-13 21:36:59] [Увлажнитель] setTargetRelativeHumidity { Error
    at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket._socket.on (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:127:13)
    at UDP.onMessage [as onmessage] (dgram.js:659:8) code: -5001 }
  thing:miio:131309276 -> (5) {"method":"set_limit_hum","params":[28],"id":5873} +6s
  miio:packet -> <Buffer 21 31 00 60 00 00 00 00 07 d3 9e dc 00 00 02 a2 62 4c 06 65 a9 3d db c6 90 8c ad b2 fd 3e 33 26> +6s
  miio:packet <- <Buffer 21 31 00 60 00 00 00 00 07 d3 9e dc 00 00 02 a3 50 59 6e 1e fc 02 6a e1 8d 28 98 5b 11 ee 5e e9> +125ms
  miio:packet <- <Buffer 21 31 00 60 00 00 00 00 07 d3 9e dc 00 00 02 a3 50 59 6e 1e fc 02 6a e1 8d 28 98 5b 11 ee 5e e9> +4ms
  thing:miio:131309276 <- Message: `{"id":5873,"error":{"code":-5001,"message":"invalid arg"}}` +136ms
[2020-3-13 21:37:05] [Увлажнитель] setTargetRelativeHumidity { Error
    at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket._socket.on (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:127:13)
    at UDP.onMessage [as onmessage] (dgram.js:659:8) code: -5001 }
  thing:miio:131309276 -> (5) {"method":"set_limit_hum","params":[25],"id":5874} +3s
  miio:packet -> <Buffer 21 31 00 60 00 00 00 00 07 d3 9e dc 00 00 02 a6 a9 83 0f ac df fc c6 b8 d0 33 e3 9f 9b 30 fd a6> +3s
  miio:packet <- <Buffer 21 31 00 60 00 00 00 00 07 d3 9e dc 00 00 02 a7 f3 b5 c7 a1 6a b3 9d 43 73 8f 48 44 86 f4 28 f2> +336ms
  miio:packet <- <Buffer 21 31 00 60 00 00 00 00 07 d3 9e dc 00 00 02 a7 f3 b5 c7 a1 6a b3 9d 43 73 8f 48 44 86 f4 28 f2> +3ms
  thing:miio:131309276 <- Message: `{"id":5874,"error":{"code":-5001,"message":"invalid arg"}}` +349ms
[2020-3-13 21:37:09] [Увлажнитель] setTargetRelativeHumidity { Error
    at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket._socket.on (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:127:13)
    at UDP.onMessage [as onmessage] (dgram.js:659:8) code: -5001 }
  thing:miio:131309276 -> (5) {"method":"set_limit_hum","params":[25],"id":5875} +3s
  miio:packet -> <Buffer 21 31 00 60 00 00 00 00 07 d3 9e dc 00 00 02 a9 10 43 3d ad da 58 03 36 dc 23 16 ec c5 9b 7e 3a> +3s
  miio:packet <- <Buffer 21 31 00 60 00 00 00 00 07 d3 9e dc 00 00 02 aa fe a6 62 d9 8c b5 29 54 89 53 56 ac b0 79 d9 5e> +89ms
  miio:packet <- <Buffer 21 31 00 60 00 00 00 00 07 d3 9e dc 00 00 02 aa fe a6 62 d9 8c b5 29 54 89 53 56 ac b0 79 d9 5e> +3ms
  thing:miio:131309276 <- Message: `{"id":5875,"error":{"code":-5001,"message":"invalid arg"}}` +101ms
[2020-3-13 21:37:12] [Увлажнитель] setTargetRelativeHumidity { Error
    at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket._socket.on (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:127:13)
    at UDP.onMessage [as onmessage] (dgram.js:659:8) code: -5001 }
`

**Comment by russtone** [comment]
Thanks @myxa27, I will try fix this

**Comment by myxa27** [comment]
After restarting the nomebridge, the following errors:

`
[2020-3-13 21:46:06] [Увлажнитель] Fail to discover the device. Retry in 1 minute { Error: Could not connect to device, handshake timeout
    at Timeout.handshakeTimeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:427:17)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5) code: 'timeout', device: null }
[2020-3-13 21:46:31] [Увлажнитель] getCurrentHumidifierState TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getCurrentHumidifierState (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:177:43)
    at Characteristic.CurrentHumidifierDehumidifierState.emit (events.js:127:13)
    at Characteristic.CurrentHumidifierDehumidifierState.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:46:31] [Увлажнитель] getLockPhysicalControls TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getLockPhysicalControls (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:297:44)
    at Characteristic.LockPhysicalControls.emit (events.js:127:13)
    at Characteristic.LockPhysicalControls.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:46:31] [Увлажнитель] getCurrentRelativeHumidity TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getCurrentRelativeHumidity (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:191:46)
    at Characteristic.CurrentRelativeHumidity.emit (events.js:127:13)
    at Characteristic.CurrentRelativeHumidity.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:46:32] [Увлажнитель] getDryingMode TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getDryingMode (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:326:42)
    at Characteristic.SwingMode.emit (events.js:127:13)
    at Characteristic.SwingMode.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:46:32] [Увлажнитель] getRotationSpeed TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getRotationSpeed (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:238:42)
    at Characteristic.RotationSpeed.emit (events.js:127:13)
    at Characteristic.RotationSpeed.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:46:32] [Увлажнитель] getWaterLevel TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getWaterLevel (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:227:48)
    at Characteristic.WaterLevel.emit (events.js:127:13)
    at Characteristic.WaterLevel.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:46:32] [Увлажнитель] getActive TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getActive (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:150:43)
    at Characteristic.Active.emit (events.js:127:13)
    at Characteristic.Active.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:46:32] [Увлажнитель] getTargetRelativeHumidity TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getTargetRelativeHumidity (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:202:47)
    at Characteristic.RelativeHumidityHumidifierThreshold.emit (events.js:127:13)
    at Characteristic.RelativeHumidityHumidifierThreshold.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:46:38] [Config] Homebridge Config UI X v4.12.0 is listening on :: port 8080
[2020-3-13 21:47:00] [Увлажнитель] getTargetRelativeHumidity TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getTargetRelativeHumidity (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:202:47)
    at Characteristic.RelativeHumidityHumidifierThreshold.emit (events.js:127:13)
    at Characteristic.RelativeHumidityHumidifierThreshold.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:47:00] [Увлажнитель] getWaterLevel TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getWaterLevel (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:227:48)
    at Characteristic.WaterLevel.emit (events.js:127:13)
    at Characteristic.WaterLevel.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:47:00] [Увлажнитель] getRotationSpeed TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getRotationSpeed (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:238:42)
    at Characteristic.RotationSpeed.emit (events.js:127:13)
    at Characteristic.RotationSpeed.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:47:00] [Увлажнитель] getDryingMode TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getDryingMode (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:326:42)
    at Characteristic.SwingMode.emit (events.js:127:13)
    at Characteristic.SwingMode.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:47:00] [Увлажнитель] getLockPhysicalControls TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getLockPhysicalControls (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:297:44)
    at Characteristic.LockPhysicalControls.emit (events.js:127:13)
    at Characteristic.LockPhysicalControls.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:47:00] [Увлажнитель] getCurrentRelativeHumidity TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getCurrentRelativeHumidity (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:191:46)
    at Characteristic.CurrentRelativeHumidity.emit (events.js:127:13)
    at Characteristic.CurrentRelativeHumidity.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:47:00] [Увлажнитель] getCurrentHumidifierState TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getCurrentHumidifierState (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:177:43)
    at Characteristic.CurrentHumidifierDehumidifierState.emit (events.js:127:13)
    at Characteristic.CurrentHumidifierDehumidifierState.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
[2020-3-13 21:47:00] [Увлажнитель] getActive TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getActive (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:150:43)
    at Characteristic.Active.emit (events.js:127:13)
    at Characteristic.Active.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:127:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:127:13)
`

**Comment by russtone** [comment]
I've committed possible fix for this issue. It seems that the problem occurred when wrong target humidity value was set. The only valid values for this parameter are: 30, 40, 50, 60, 70, 80

**Comment by ArielZgo** [comment]
Hi, I also have "not responding in Apple Home" with this error. Could you please take a look? 

[3/29/2020, 7:09:09 PM] [Humidifier] getActive { Error: busy.
    at Object.reject (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket._socket.on (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:189:13)
    at UDP.onMessage [as onmessage] (dgram.js:685:8) code: -30012 }
[3/29/2020, 7:09:09 PM] [Humidifier] getTargetRelativeHumidity { Error: busy.
    at Object.reject (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket._socket.on (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:189:13)
    at UDP.onMessage [as onmessage] (dgram.js:685:8) code: -30012 }
[3/29/2020, 7:09:09 PM] [Humidifier] getCurrentRelativeHumidity { Error: busy.
    at Object.reject (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket._socket.on (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:189:13)
    at UDP.onMessage [as onmessage] (dgram.js:685:8) code: -30012 }
[3/29/2020, 7:09:09 PM] [Humidifier] getCurrentHumidifierState { Error: busy.
    at Object.reject (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket._socket.on (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:189:13)
    at UDP.onMessage [as onmessage] (dgram.js:685:8) code: -30012 }

**Comment by iShift** [comment]
Have same problem: 
When i open Apple Home i get No response from Humidifier, but if i change room and get back to favoritisms screen - humidifier get status as normal.

**Comment by MaksimChikulin** [comment]
after the update there is still an error:

[12.04.2020, 14:36:57] [HumidifierB] getCurrentTemperature Error: busy.
    at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:910:8) {
  code: -30012
}
[12.04.2020, 14:36:57] [HumidifierB] getCurrentRelativeHumidity Error: busy.
    at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:910:8) {
  code: -30012
}

**Comment by eugensubachev** [comment]
>after the update there is still an error: ...

@MaksimChikulin same issues

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iShift** [comment]
same :(

**Comment by iShift** [comment]
Looks like last commit fixed bug for me, thanks @PietroLubini

**Comment by MaksimChikulin** [comment]
I don't see any errors in the logs or the "No connection" error in Home Kits after update, Thank's!! but the device update time for the "ca1" model has increased to 2-3 seconds.

**Comment by ileodo** [comment]
fixed in the latest release. thanks. feel free to close.
