### ISSUE TITLE
zhimi.humidifier.ca4 Fail to get props. SocketError

### ISSUE THREAD

**Issue by russtone** [russtone/homebridge-mi-humidifier#50]
> > I've also noticed same spam in logs with this error: 'Fail to get props. SocketError: Timeout', it seems issue is not resolved. I've also mentioned this in #46
> 
> Are you getting these errors for jsq model?

I have `zhimi.humidifier.ca4` model. If this may help, I have two same devices connected with your plugin, maybe there is any complication if more than one device is connected?

_Originally posted by @lvtz in https://github.com/russtone/homebridge-mi-humidifier/issues/47#issuecomment-748007204_

**Comment by russtone** [comment]
Hey @lvtz,
No, there shouldn't be any problems with multiple devices, because separate object is created for every device.

**Comment by lvtz** [comment]
> Hey @lvtz,
> No, there shouldn't be any problems with multiple devices, because separate object is created for every device.

So what could be causing this random issue? Everything works fine, but from time to time I see a lot of spam with this error in my logs.

**Comment by russtone** [comment]
There was error with "updateInterval" property from config, its value wasn't multiplied by 1000 to get seconds. So update happened every 30ms, which could cause this problem.
I've published a new version, please test it

**Comment by lvtz** [comment]
Thank you for fast investigation. I've just updated to new version, hope it will help :)

**Comment by lvtz** [comment]
Spam error no longer occurs. But could we somehow handle this error, instead of throwing full error? Can we just publish one-line information about? I think the end user has no influence on the Timeout, so additional information about the error is unnecessary.

My proposal:

Before
![obraz](https://user-images.githubusercontent.com/18595528/102620740-cabb9180-413e-11eb-9795-6c5d950c0b0c.png)

After
![obraz](https://user-images.githubusercontent.com/18595528/102620842-f9396c80-413e-11eb-9515-28512355180d.png)

**Comment by russtone** [comment]
> Spam error no longer occurs. But could we somehow handle this error, instead of throwing full error? Can we just publish one-line information about? I think the end user has no influence on the Timeout, so additional information about the error is unnecessary.
> 
> My proposal:
> 
> Before
> ![obraz](https://user-images.githubusercontent.com/18595528/102620740-cabb9180-413e-11eb-9795-6c5d950c0b0c.png)
> 
> After
> ![obraz](https://user-images.githubusercontent.com/18595528/102620842-f9396c80-413e-11eb-9515-28512355180d.png)

Yes, I'll try to show better error messages

**Comment by Dane03** [comment]
Well I still see these fail to get props errors every (now) 30 seconds.

Is there a fix for this on the way?

**Comment by russtone** [comment]
> Well I still see these fail to get props errors every (now) 30 seconds.
> 
> Is there a fix for this on the way?

Do you also have `zhimi.humidifier.ca4` model?
Do you see this error and the plugin is still working?

**Comment by Dane03** [comment]
I have 2 of the first gen, some more ca4 ;-)

As the error doesn't tell on which device it occurs... hard to tell.

But yes, all working currently, no issues, just this regular appearing error.

But as I have disabled Buzzer, led etc as I never change these, we have to ask someone else if that works now.

Thanks for your work, really appreciate it!

**Comment by mbrandau** [comment]
I have a ca4. Does not work at all:
```
[12/25/2020, 12:09:07 PM] [MiHumidifier] Fail to get props. SocketError: Timeout
    at /homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:31
    at done (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:106:7)
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[12/25/2020, 12:09:23 PM] [MiHumidifier] Fail to set property 'power'. SocketError: Timeout
    at /homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:31
    at done (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:106:7)
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by russtone** [comment]
> I have a ca4. Does not work at all:
> 
> ```
> [12/25/2020, 12:09:07 PM] [MiHumidifier] Fail to get props. SocketError: Timeout
>     at /homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:31
>     at done (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:106:7)
>     at Timeout.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:13)
>     at listOnTimeout (internal/timers.js:549:17)
>     at processTimers (internal/timers.js:492:7)
> [12/25/2020, 12:09:23 PM] [MiHumidifier] Fail to set property 'power'. SocketError: Timeout
>     at /homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:31
>     at done (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:106:7)
>     at Timeout.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:125:13)
>     at listOnTimeout (internal/timers.js:549:17)
>     at processTimers (internal/timers.js:492:7)
> ```
> 
> Plugin version: v2.0.0-beta.7
> Firmware version: 2.1.3.0015

It looks likes invalid IP address or token issue. It will be helpful if you collect some debug logs by running homebridge like this `DEBUG=miio-api* homebrdige`

**Comment by mbrandau** [comment]
> It looks likes invalid IP address or token issue.
@russtone the IP address in confirmed. I doubled checked by pinging and through the Xiaomi Home app. I got the token with `npx miio discover`. I will try to run it with debug log. Will take some fiddling since I have it running in a container.

**Comment by mchechin** [comment]
@russtone same problem here. My ca1 works well, but ca4 does not at all.

`[MiHumidifier] Fail to get props. SocketError: Timeout
    at /usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:131:31
    at done (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:112:7)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:131:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

**Comment by Dane03** [comment]
Strange that my ca4s work perfectly fine, as do my ca1...

**Comment by mbrandau** [comment]
> Strange that my ca4s work perfectly fine, as do my ca1...

@Dane03 would you like to share your config? Are there any differences to mine?
My configuration:
```
{
    "devices": [
        {
            "name": "xxx",
            "address": "xxx",
            "token": "xxx",
            "model": "zhimi.humidifier.ca4",
            "updateInterval": 30,
            "temperatureSensor": {
                "enabled": true,
                "name": "xxx"
            },
            "humiditySensor": {
                "enabled": true,
                "name": "xxx"
            },
            "ledBulb": {
                "enabled": false,
                "name": "xxx"
            },
            "buzzerSwitch": {
                "enabled": false,
                "name": "xxx"
            }
        }
    ],
    "platform": "MiHumidifier"
}
```

**Comment by Dane03** [comment]
`{
                    "address": "192.168.178.41",
                    "buzzerSwitch": {
                        "enabled": false,
                        "name": "Luftbefeuchter Kinderzimmer Buzzer"
                    },
                    "humiditySensor": {
                        "enabled": false,
                        "name": "Luftbefeuchter Kinderzimmer Humidity"
                    },
                    "ledBulb": {
                        "enabled": false,
                        "name": "Luftbefeuchter Kinderzimmer LED"
                    },
                    "model": "zhimi.humidifier.ca1",
                    "name": "Luftbefeuchter Kinderzimmer",
                    "temperatureSensor": {
                        "enabled": false,
                        "name": "Luftbefeuchter Kinderzimmer Temperature"
                    },
                    "token": "4d79a1ade0d2392c38b92e983b188061",
                    "updateInterval": 30
                },`

**Comment by mchechin** [comment]
@mbrandau 
Okay, so I finally figured it out.
Previously I obtained my tokens by connecting to the Wi-Fi network of the device (when it was in reset mode) and ran "miio discover" command. 
Now I tried to obtain them using [this method (iOS backup)](https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md) and I got completely different tokens and all worked with these ones.

**Comment by mbrandau** [comment]
@mchechin this worked for me too. Works as expected 👍

**Comment by mbrandau** [comment]
Maybe a link to a guide for obtaining the token in the README would be helpful.

**Comment by Dane03** [comment]
Fo you guys still get the error, even though everything works now?

**Comment by mchechin** [comment]
@Dane03 No errors showing for me. All logs are sweet and clear.

**Comment by russtone** [comment]
> Maybe a link to a guide for obtaining the token in the README would be helpful.

I'll add this link to README. Thanks!

**Comment by russtone** [comment]
> Fo you guys still get the error, even though everything works now?

I've published new version with better logging. Now log messages contain device IP address, so you can find which device produce this errors

**Comment by russtone** [comment]
Issue seems to be fixed, so I'm closing this.
